name: Release
on:
  push:
    tags:
      - "*"
jobs:
  test:
    name: Test
    strategy:
      matrix:
        id:
          - hello1
          - hello2
    runs-on: ubuntu-latest
    steps:
      - name: Create assets
        run: |
          touch {{ matrix.id }}.txt
          mkdir -p sub
          touch sub/{{ matrix.id }}.txt
          tar czf {{ matrix.id }}.tar.gz {{ matrix.id }}.txt sub
      - name: Create release
        id: create-release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: {{ matrix.id }}.tar.gz
          asset_name: {{ matrix.id }}.tar.gz
          asset_content_type: application/gzip
