name: Windows
on:
  - push
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Set culture
        run: |
          Get-Culture
          [CultureInfo]::CurrentCulture = "ja-JP"
          Get-Culture
      - name: Set locale
        run: |
          Set-WinSystemLocale ja-JP
          Start-Sleep -s 10
          Restart-Computer
      - name: Set system culture
        run: |
          Get-Culture
          Set-Culture "ja-JP"
          Get-Culture
      - name: Show culture
        run: |
          Get-Culture
