name: Windows
on:
  - push
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Set culture
        run: |
          Get-Culture
          [CultureInfo]::CurrentCulture = "ja-JP"
          Get-Culture
      - name: Set system culture
        run: |
          Get-Culture
          Set-Culture "ja-JP"
          Get-Culture
      - name: Show culture
        run: |
          Get-Culture
